### ISSUE TITLE
Newly-created RED console/terminal via CMD does now allow Left, Right Navigation or Up Arrow History 

### ISSUE THREAD

**Issue by mbennette68** [red/VScode-extension#49]
Hello,

Apologies if the following does not qualify as a bug and there is a way to enable it but I was not able to find it.

I have encountered an issue where invoking the red console from within VSCode CMD window brings up red interpreter inside VS Code but it lacks **Left** (**←**), **Right** (**→**) **Arrow** navigation or **Up Arrow** (**↑**) **History Recall** in a newly-created RED console/terminal. The end effect is that pressing any of those keys (**←↑→**) on the keyboard has no effect. That being said, the **Enter** & **Backspace** keys work.

Basically, I setup the path to point to a renamed red (**red-exe.exe**) executable which I can invoke via a batch file called **redng.bat** from any DOS Window.  When called outside of VS Code, the functionality of those keys, (**←↑→**), works just fine.
******************************************
**redng.bat**
--------------------------------------------
@echo off
cls
"%~dp0red-exe.exe" --cli %*

As mentioned, I have looked around and have not found any settings that would enable that functionality after calling the batch file in my Windows 10 machine, latest VS Code and VS Code Red extension as of 12/17/20.

Best regards,
MB

**Comment by qtxie** [comment]
The issue is that VSCode's terminal doesn't pass the ENHANCED_KEY modifier to red console as other terminals does.
I changed the logic to detect those arrow keys in the red console. Please try the latest version of Red.
Fixed by commit https://github.com/red/red/commit/6a7d9f5485b23320d63c1e8bd9b12651bfae1105

**Comment by mbennette68** [comment]
Hello, 
I tried to update the Red Extension in VS Code as well as recompiled the Red Console at **C:\ProgramData\Red** with **red.exe --cli** but it still does not work. I made a quick screen capture video to show what is happening: [Key Issues in Red Console of VSCode Extension](https://filebin.net/05f2n04ssp6le7xg/vs_code_red_console_key_issue.mp4?t=aou0ehck)

Thank you,
MB

**Comment by qtxie** [comment]
@mbennette68 The automated build red binary on red-lang.org were built 3 days ago, not the latest one. The commit https://github.com/red/red/commit/6a7d9f5485b23320d63c1e8bd9b12651bfae1105 didn't trigger a new build for red binary. I'll let you know when it's online.

**Comment by mbennette68** [comment]
@qtxie The updated fixes incorporated in **red-19dec20-d082313c5.exe** worked!
I was able to use the **Left (←), Right (→) Arrow, Up Arrow (↑) History Recall** navigation with VS Code.

Thank you for your help,
MB
